/**
 * 
 */
package org.purl.linkedepcis.cbv;

/**
 * @author monika
 *
 */
public enum BusinessStep {
	
	ACCEPTING, ARRIVING, COMMISSIONING, ASSEMBLING, COLLECTING, DECOMMISSIONING, DEPARTING, DESTROYING,
	DISASSEMBLING, ENTERING_EXITING, HOLDING, INSPECTING, INSTALLING, KILLING, LOADING, OTHER, PACKING, PICKING, 
	RECEIVING, REMOVING, REPACKING, REPLACING, RESERVING, RETAIL_SELLING, SHIPPING, STOCKING, STORING, TRANSFORMING

}
