/**
 * 
 */
package org.purl.linkedepcis.cbv;

/**
 * @author monika
 *
 */
public enum Disposition {

	ACTIVE, CONTAINER_CLOSED, DESTROYED, ENCODED, IN_PROGRESS, IN_TRANSIT, INACTIVE, 
	NON_SELLABLE_DAMAGED, NON_SELLABLE_DISPOSED, NON_SELLABLE_EXPIRED, NON_SELLABLE_NO_PEDIGREE_MATCH,
    NON_SELLABLE_RECORD, NON_SELLABLE_OTHER, RESERVED, RETAIL_SOLD, RETURNED, SELLABLE_ACCESSIBLE, 
    SELLABLE_NOT_ACCESSIBLE, UNKNOWN
    
	
}
